import { useState } from "react";
import FileDropZone from "../components/FileDropZone";

const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:5000/api";

function readFilenameFromHeader(disposition, fallback) {
  if (!disposition) {
    return fallback;
  }

  const match = disposition.match(/filename="?([^\";]+)"?/i);
  return match ? match[1] : fallback;
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function DecryptPage() {
  const [file, setFile] = useState(null);
  const [privateKey, setPrivateKey] = useState("");
  const [status, setStatus] = useState("Idle");
  const [busy, setBusy] = useState(false);

  async function decryptNow() {
    if (!file) {
      setStatus("Please select a .hybrid payload file.");
      return;
    }

    if (!privateKey.trim()) {
      setStatus("Please provide the private key.");
      return;
    }

    setBusy(true);
    setStatus("Decrypting payload and verifying GCM auth tag...");

    try {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("privateKey", privateKey);

      const response = await fetch(`${API_BASE}/decrypt`, {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const body = await response.json().catch(() => ({ message: "Decryption failed" }));
        throw new Error(body.message || "Decryption failed");
      }

      const blob = await response.blob();
      const disposition = response.headers.get("Content-Disposition");
      const fallback = file.name.replace(/\.hybrid$/i, "") || "decrypted_file";
      const outputName = readFilenameFromHeader(disposition, fallback);

      downloadBlob(outputName, blob);
      setStatus("Decryption successful. Original file downloaded.");
    } catch (error) {
      setStatus(error.message || "Decryption failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="panel-grid">
      <div className="card">
        <h2>Receiver flow</h2>
        <p>Upload .hybrid payload generated by sender.</p>
        <FileDropZone
          id="decrypt-source"
          label="Upload .hybrid payload"
          accept=".hybrid,application/octet-stream,text/plain"
          file={file}
          onFileSelect={setFile}
        />
      </div>

      <div className="card">
        <h2>Private key</h2>
        <p>Paste matching RSA private key to recover the original file.</p>
        <textarea
          value={privateKey}
          onChange={(event) => setPrivateKey(event.target.value)}
          placeholder="-----BEGIN PRIVATE KEY-----"
          rows={10}
        />
        <div className="actions">
          <button type="button" className="primary" onClick={decryptNow} disabled={busy}>
            Decrypt
          </button>
        </div>
      </div>

      <p className="status">{status}</p>
    </section>
  );
}

export default DecryptPage;
